apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-monitor
spec:
  selector:
    matchLabels:
      app: service-monitor
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: service-monitor
    spec:
      containers:
      - name: service-monitor
        image: ddbyro/service-monitor:0.0.1
        ports:
        - containerPort: 80
