apiVersion: v1
kind: ConfigMap
metadata:
  name: service-monitor
  # namespace: default
data:
  config.yaml: |
    prod_services:
      {{- range .Values.prod_service_config }}
      - name: {{ .name}}
        environment: '{{ .environment }}'
        hostname: '{{ toYaml .hostname }}'
        version: '{{ toYaml .version }}'
      {{ end }}

    stage_services:
      {{- range .Values.stage_service_config }}
      - name: {{ .name}}
        environment: '{{ .environment }}'
        hostname: '{{ toYaml .hostname }}'
        version: '{{ toYaml .version }}'
      {{ end }}

    dev_services:
      {{- range .Values.dev_service_config }}
      - name: {{ .name}}
        environment: '{{ .environment }}'
        hostname: '{{ toYaml .hostname }}'
        version: '{{ toYaml .version }}'
      {{ end }}