apiVersion: v1
kind: ConfigMap
metadata:
  name: service-monitor
  namespace: default
data:
  config.yaml: |
    services:
      {{- range .Values.service_config }}
      - name: {{ .name}}
        environment: '{{ .environment }}'
        hostname: '{{ toYaml .hostname }}'
        version: '{{ toYaml .version }}'
      {{ end }}