apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: service-monitor
  name: service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: service-monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-monitor
    spec:
      containers:
      - image: ddbyro/service-monitor:0.0.1
        imagePullPolicy: IfNotPresent
        name: service-monitor
        ports:
        - containerPort: 5002
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30