apiVersion: v1
kind: Service
metadata:
  name: service-monitor
  # namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app.kubernetes.io/name: service-monitor
  sessionAffinity: None
  type: LoadBalancer