image:
  repository: ddbyro/service-monitor
  pullPolicy: IfNotPresent
  tag: 0.0.4

strategy:
  type: Recreate

service:
  port: 5002

prod_service_config:
  - name: Hass
    environment: Prod
    hostname: https://hass.dbyron.space/
    version: 0.1.0

stage_service_config:
  - name: Plex
    environment: Prod
    hostname: https://plex.dbyron.space:32400/web/index.html#
    version: 0.1.0

dev_service_config:
  - name: Google
    environment: Prod
    hostname: https://www.google.com/
    version: 0.1.0
  - name: duckduckgo
    environment: Prod
    hostname: https://duckduckgo.com/
    version: 0.1.0
