image:
  repository: ddbyro/service-monitor
  pullPolicy: IfNotPresent
  tag: 0.0.2

strategy:
  type: Recreate

service:
  port: 5002

service_config:
  - name: Hass
    environment: Prod
    hostname: https://hass.dbyron.space/
    version: 0.1.0
  - name: Plex
    environment: Prod
    hostname: https://plex.dbyron.space:32400/web/index.html#
    version: 0.1.0
  - name: Google
    environment: Prod
    hostname: https://www.google.com/
    version: 0.1.0
  - name: duckduckgo
    environment: Prod
    hostname: https://duckduckgo.com/
    version: 0.1.0
